### ISSUE TITLE
Tau

### ISSUE THREAD

**Issue by juriad** [mjiricka/xkb-czech-ucw-extension#1]
Please add support for Greek_tau as 
`key <AE03> { [ Greek_pi, Greek_tau ] };`
The reason for this is https://tauday.com/tau-manifesto

**Comment by mjiricka** [comment]
Hello @juriad , thank you for your idea. I am curious to know are you using this extension for anything? Or are you just spreading the fame of Tau manifesto?

**Comment by juriad** [comment]
Actually, it came to naming my team Tau through a couple of associations (competition uses "360").
I've been using your UCW extension for a couple of months and noticed that it types π with and without Shift, so extending it by putting τ above π naturally crossed my mind.
My motivation is purely personal; I mentioned the manifesto as it explains the relationship between τ and π and to . I am already using my patched version. 😃

**Comment by mjiricka** [comment]
Ok, I added τ.

I am delighted someone else using this repo ;) I would like to extend it even more. For example to add another modifier key instead of the strange key next to left shift (with pipe and back slash) on 105 ISO keyboards. And use this key to map arrows and numerical keys on keys like "j", "k", "l", etc. I think it should be possible with xkb, but my first attempts failed. Any input on this is welcome ;)
